package com.github.s262316.forx.newbox;

public enum AnonReason
{
	INLINE_CONTAINER,
	TABLE_CONTAINER,
	INLINE_BLOCK_ROOT_CONTAINER,
	ROW,
	CELL,
	COLUMN,
	BLOCK_INSIDE_INLINE_SPLIT_CONTAINER,
	BLOCK_INSIDE_INLINE_POST_SPLIT_STRUCTURE
}
